name: bmi_calculator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.3.0
  responsive_framework: ^0.0.14

flutter:
  uses-material-design: true

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/ic_launcher.png"

flutter_native_splash:
  color: "#e1f5fe"
